// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Problems.API.Data;

#nullable disable

namespace Problems.API.Migrations
{
    [DbContext(typeof(ProblemDbContext))]
    partial class ProblemDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Problems.API.Domain.Problem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Completed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Index")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LifeAreaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Plan")
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwentyPercent")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("User_Id")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Problems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Completed = true,
                            Index = 1,
                            LifeAreaId = 1,
                            Text = "Not able to speak in english",
                            TwentyPercent = true,
                            User_Id = new Guid("16591e7e-c974-4512-88aa-af31e5230c93")
                        },
                        new
                        {
                            Id = 2,
                            Completed = true,
                            Index = 2,
                            LifeAreaId = 1,
                            Text = "Lack of sales man skill",
                            TwentyPercent = true,
                            User_Id = new Guid("16591e7e-c974-4512-88aa-af31e5230c93")
                        },
                        new
                        {
                            Id = 3,
                            Completed = true,
                            Index = 3,
                            LifeAreaId = 1,
                            Text = "Build product from scratch",
                            TwentyPercent = true,
                            User_Id = new Guid("16591e7e-c974-4512-88aa-af31e5230c93")
                        },
                        new
                        {
                            Id = 4,
                            Completed = true,
                            Index = 1,
                            LifeAreaId = 1,
                            Text = "Business mindset",
                            TwentyPercent = true,
                            User_Id = new Guid("16591e7e-c974-4512-88aa-af31e5230c93")
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
