global using BuildingBlocks.CQRS;
global using Objectives.API.Dto;
global using BuildingBlocks.Exceptions;
global using FluentValidation;
global using Carter;
global using Mapster;
global using MediatR;
global using BuildingBlocks.Helper;
global using Objectives.API.Data;